#!/bin/bash
# -*- shell-script -*-

#
# Install -- libinstall.sh を使って定義済みのパッケージのインストールとリンクを行う。
#

#set -x    # デバッグ時には -x オプションをつける
#set -e    # source して使うときは、-e をつけない

_SRC_DIR=$(pwd)
_PROGNAME="$0"

# デフォルトでは強制再インストールはしない。
[[ -z "$_FORCE" ]] && _FORCE="false"

# デフォルトでは、メッセージを出力する。
[[ -z "$_VERBOSE" ]] && _VERBOSE="true"

source ./libinstall.sh

dots_install
dots_deploy
